onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider UUT
add wave -noupdate /fofb_cc_fod_tb/uut/BPMS
add wave -noupdate /fofb_cc_fod_tb/uut/DEVICE
add wave -noupdate /fofb_cc_fod_tb/uut/INTERLEAVED
add wave -noupdate /fofb_cc_fod_tb/uut/LaneCount
add wave -noupdate /fofb_cc_fod_tb/uut/mgtclk_i
add wave -noupdate /fofb_cc_fod_tb/uut/sysclk_i
add wave -noupdate /fofb_cc_fod_tb/uut/mgtreset_i
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_valid_i
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_start_i
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_end_i
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_dly_i
add wave -noupdate /fofb_cc_fod_tb/uut/linksup_i
add wave -noupdate /fofb_cc_fod_tb/uut/fod_dat_i
add wave -noupdate /fofb_cc_fod_tb/uut/fod_dat_val_i
add wave -noupdate /fofb_cc_fod_tb/uut/fod_dat_o
add wave -noupdate /fofb_cc_fod_tb/uut/fod_dat_val_o
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_cntr_i
add wave -noupdate /fofb_cc_fod_tb/uut/timestamp_val_i
add wave -noupdate /fofb_cc_fod_tb/uut/bpm_x_pos_i
add wave -noupdate /fofb_cc_fod_tb/uut/bpm_y_pos_i
add wave -noupdate /fofb_cc_fod_tb/uut/pos_datsel_i
add wave -noupdate /fofb_cc_fod_tb/uut/txf_full_i
add wave -noupdate /fofb_cc_fod_tb/uut/bpmid_i
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_dout_o
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_addr_i
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_rstb_i
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_long_en_i
add wave -noupdate /fofb_cc_fod_tb/uut/fodprocess_time_o
add wave -noupdate /fofb_cc_fod_tb/uut/bpm_count_o
add wave -noupdate /fofb_cc_fod_tb/uut/golden_orb_x_i
add wave -noupdate /fofb_cc_fod_tb/uut/golden_orb_y_i
add wave -noupdate /fofb_cc_fod_tb/uut/fofb_watchdog_i
add wave -noupdate /fofb_cc_fod_tb/uut/fofb_event_i
add wave -noupdate /fofb_cc_fod_tb/uut/fofb_dma_ok_i
add wave -noupdate /fofb_cc_fod_tb/uut/fofb_node_mask_o
add wave -noupdate /fofb_cc_fod_tb/uut/toa_rstb_i
add wave -noupdate /fofb_cc_fod_tb/uut/toa_rden_i
add wave -noupdate /fofb_cc_fod_tb/uut/toa_dat_o
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_rstb_i
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_rden_i
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_dat_o
add wave -noupdate /fofb_cc_fod_tb/uut/pload_header
add wave -noupdate /fofb_cc_fod_tb/uut/bpm_cnt
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_start
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_valid
add wave -noupdate /fofb_cc_fod_tb/uut/bpm_xpos_val
add wave -noupdate /fofb_cc_fod_tb/uut/bpm_ypos_val
add wave -noupdate /fofb_cc_fod_tb/uut/pmc_xpos_val
add wave -noupdate /fofb_cc_fod_tb/uut/pmc_ypos_val
add wave -noupdate /fofb_cc_fod_tb/uut/fod_idat
add wave -noupdate /fofb_cc_fod_tb/uut/time_stamp_cnt
add wave -noupdate /fofb_cc_fod_tb/uut/fod_completed
add wave -noupdate /fofb_cc_fod_tb/uut/fod_completed_prev
add wave -noupdate /fofb_cc_fod_tb/uut/fod_idat_val
add wave -noupdate /fofb_cc_fod_tb/uut/fod_odat
add wave -noupdate /fofb_cc_fod_tb/uut/fod_odat_val
add wave -noupdate /fofb_cc_fod_tb/uut/posmem_wea_prev
add wave -noupdate /fofb_cc_fod_tb/uut/posmem_addra_prev
add wave -noupdate /fofb_cc_fod_tb/uut/buffer_write_sw
add wave -noupdate /fofb_cc_fod_tb/uut/buffer_read_sw
add wave -noupdate /fofb_cc_fod_tb/uut/xpos_to_read
add wave -noupdate /fofb_cc_fod_tb/uut/ypos_to_read
add wave -noupdate /fofb_cc_fod_tb/uut/own_packet_to_inject
add wave -noupdate /fofb_cc_fod_tb/uut/own_xpos_to_store
add wave -noupdate /fofb_cc_fod_tb/uut/own_ypos_to_store
add wave -noupdate /fofb_cc_fod_tb/uut/xpos_to_store
add wave -noupdate /fofb_cc_fod_tb/uut/ypos_to_store
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_addr
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_addr_intrlvd
add wave -noupdate /fofb_cc_fod_tb/uut/fofb_nodemask
add wave -noupdate /fofb_cc_fod_tb/uut/fofb_nodemask_sys
add wave -noupdate /fofb_cc_fod_tb/uut/posmem_wea
add wave -noupdate /fofb_cc_fod_tb/uut/posmem_addra
add wave -noupdate /fofb_cc_fod_tb/uut/posmem_addrb
add wave -noupdate /fofb_cc_fod_tb/uut/bpmid
add wave -noupdate /fofb_cc_fod_tb/uut/fod_id
add wave -noupdate /fofb_cc_fod_tb/uut/fod_xpos
add wave -noupdate /fofb_cc_fod_tb/uut/fod_ypos
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_dout
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_dout_intrlvd
add wave -noupdate /fofb_cc_fod_tb/uut/bpm_count_prev
add wave -noupdate /fofb_cc_fod_tb/uut/maskmem_sw
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemA_addra
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemA_addrb
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemA_dina
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemA_doutb
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemA_wea
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemB_addra
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemB_addrb
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemB_dina
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemB_doutb
add wave -noupdate /fofb_cc_fod_tb/uut/maskmemB_wea
add wave -noupdate /fofb_cc_fod_tb/uut/maskmem_clear
add wave -noupdate /fofb_cc_fod_tb/uut/maskmem_clear_cnt
add wave -noupdate /fofb_cc_fod_tb/uut/fod_ok_n
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_end_sys
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_cnt
add wave -noupdate /fofb_cc_fod_tb/uut/timeframe_inject
add wave -noupdate /fofb_cc_fod_tb/uut/posmem_xweb
add wave -noupdate /fofb_cc_fod_tb/uut/posmem_yweb
add wave -noupdate /fofb_cc_fod_tb/uut/toa_min_val
add wave -noupdate /fofb_cc_fod_tb/uut/toa_max_val
add wave -noupdate /fofb_cc_fod_tb/uut/toa_min_wr
add wave -noupdate /fofb_cc_fod_tb/uut/toa_max_wr
add wave -noupdate /fofb_cc_fod_tb/uut/toamem_wea
add wave -noupdate /fofb_cc_fod_tb/uut/toamem_web
add wave -noupdate /fofb_cc_fod_tb/uut/toamem_addra
add wave -noupdate /fofb_cc_fod_tb/uut/toamem_addrb
add wave -noupdate /fofb_cc_fod_tb/uut/toamem_dina
add wave -noupdate /fofb_cc_fod_tb/uut/toamem_dinb
add wave -noupdate /fofb_cc_fod_tb/uut/toamem_doutb
add wave -noupdate /fofb_cc_fod_tb/uut/toa_min_new
add wave -noupdate /fofb_cc_fod_tb/uut/toa_max_new
add wave -noupdate /fofb_cc_fod_tb/uut/toa_rden
add wave -noupdate /fofb_cc_fod_tb/uut/toa_rden_prev
add wave -noupdate /fofb_cc_fod_tb/uut/toa_rden_rise
add wave -noupdate /fofb_cc_fod_tb/uut/toa_addr
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_val
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_val_wr
add wave -noupdate /fofb_cc_fod_tb/uut/rcbmem_wea
add wave -noupdate /fofb_cc_fod_tb/uut/rcbmem_web
add wave -noupdate /fofb_cc_fod_tb/uut/rcbmem_addra
add wave -noupdate /fofb_cc_fod_tb/uut/rcbmem_addrb
add wave -noupdate /fofb_cc_fod_tb/uut/rcbmem_dina
add wave -noupdate /fofb_cc_fod_tb/uut/rcbmem_dinb
add wave -noupdate /fofb_cc_fod_tb/uut/rcbmem_doutb
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_val_new
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_rden
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_rden_prev
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_rden_rise
add wave -noupdate /fofb_cc_fod_tb/uut/rcb_addr
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_rd_sw
add wave -noupdate /fofb_cc_fod_tb/uut/xy_buf_rd_sw_prev
add wave -noupdate -divider frame_ctrl
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/DEVICE
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/LaneCount
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/mgtclk_i
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/mgtreset_i
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/tfs_bpm_i
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/tfs_pmc_i
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/tfs_override_i
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_len_i
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_start_o
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_end_o
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_valid_o
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/pmc_timeframe_cntr_i
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/pmc_timestamp_val_i
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_cntr_o
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timestamp_value_o
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_state
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/tfbit_mgt_ored
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_cntr
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/pmc_timeframe_val
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_start
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/counter_16bit
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/counter_10bit
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_valid
add wave -noupdate /fofb_cc_fod_tb/fofb_cc_frame_cntrl/timeframe_valid_prev
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {217857343 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1048576 ns}
